chg: usr: make resize-helper script stand-alone, add systemd support
Signed-off-by: Stephen L Arnold <sarnold@vctlabs.com>

diff --git a/recipes-core/resize-helper/files/resize-last.init b/recipes-core/resize-helper/files/resize-last.init
--- a/recipes-core/resize-helper/files/resize-last.init
+++ b/recipes-core/resize-helper/files/resize-last.init
@@ -23,49 +23,15 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 
-set -e
+### BEGIN INIT INFO
+# Provides:             resize-helper
+# Required-Start:       $local_fs
+# Required-Stop:      $local_fs
+# Default-Start:        S
+# Default-Stop:
+# Short-Description:  Resize the last partition
+### END INIT INFO
 
-do_expand_rootfs(){
-    # we must be root
-    [ $(whoami) = "root" ] || { echo "E: You must be root" && exit 1; }
-
-    # we must have few tools
-    SGDISK=$(which sgdisk) || { echo "E: You must have sgdisk" && exit 1; }
-    PARTED=$(which parted) || { echo "E: You must have parted" && exit 1; }
-    PARTPROBE=$(which partprobe) || { echo "E: You must have partprobe" && exit 1; }
-    RESIZE2FS=$(which resize2fs) || { echo "E: You must have resize2fs" && exit 1; }
-    BLKID=$(which blkid) || { echo "E: You must have blkid" && exit 1; }
-
-    # find root device
-    ROOT_DEVICE=$(findmnt / -o source -n)
-    # prune root device (for example UUID)
-    ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
-    echo "Found root device: $ROOT_DEVICE"
-    # get the partition number and type
-    ROOT_PART_NAME=$(echo "$ROOT_DEVICE" | cut -d "/" -f 3)
-    DEVICE_NAME=$(echo /sys/block/*/"${ROOT_PART_NAME}" | cut -d "/" -f 4)
-    DEVICE="/dev/${DEVICE_NAME}"
-    # get the last partition whether root or not
-    PART_ENTRY_NUMBER=$(ls /sys/block/${DEVICE_NAME}/*/partition | wc -l)
-    echo "Expanding part number: $PART_ENTRY_NUMBER"
-    PART_TABLE_TYPE=$(${BLKID} -o value -s PTTYPE "${DEVICE}")
-    DEVICE_SIZE=$(cat "/sys/block/${DEVICE_NAME}/size")
-    END_SIZE=$((DEVICE_SIZE - 1))
-
-    # in case the root device is not on a partitioned media
-    if [ "x$PART_ENTRY_NUMBER" = "x" ]; then
-        ${RESIZE2FS} "${ROOT_DEVICE}"
-        exit 0
-    fi
-
-    if [ "$PART_TABLE_TYPE" = "gpt" ]; then
-        ${SGDISK} -e ${DEVICE}
-        ${PARTPROBE}
-    fi
-    ${PARTED} ${DEVICE} resizepart ${PART_ENTRY_NUMBER} 100%
-    ${PARTPROBE}
-    ${RESIZE2FS} "${ROOT_DEVICE}"
-}
 
 case "$1" in
   start)
@@ -73,11 +39,11 @@ case "$1" in
 
     echo "Expanding last partition..."
 
-    if do_expand_rootfs  ;
+    if /usr/sbin/resize-helper ;
     then
-      echo "Expanding partition success"
+        echo "Expanding partition success"
     else
-      echo "Expanding partition has failed, see log files. Error code: $?"
+        echo "Expanding partition has failed, see log files. Error code: $?"
     fi
 
     update-rc.d -f resize-rootfs remove >/dev/null 2>&1
