fix: dev: remove double-quotes around sysfs path in resize, add some output
Signed-off-by: Stephen L Arnold <sarnold@vctlabs.com>

diff --git a/recipes-core/resize-helper/files/resize-last.init b/recipes-core/resize-helper/files/resize-last.init
--- a/recipes-core/resize-helper/files/resize-last.init
+++ b/recipes-core/resize-helper/files/resize-last.init
@@ -40,12 +40,14 @@ do_expand_rootfs(){
     ROOT_DEVICE=$(findmnt / -o source -n)
     # prune root device (for example UUID)
     ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
+    echo "Found root device: $ROOT_DEVICE"
     # get the partition number and type
     ROOT_PART_NAME=$(echo "$ROOT_DEVICE" | cut -d "/" -f 3)
     DEVICE_NAME=$(echo /sys/block/*/"${ROOT_PART_NAME}" | cut -d "/" -f 4)
     DEVICE="/dev/${DEVICE_NAME}"
     # get the last partition whether root or not
-    PART_ENTRY_NUMBER=$(ls "/sys/block/${DEVICE_NAME}/*/partition" | wc -l)
+    PART_ENTRY_NUMBER=$(ls /sys/block/${DEVICE_NAME}/*/partition | wc -l)
+    echo "Expanding part number: $PART_ENTRY_NUMBER"
     PART_TABLE_TYPE=$(${BLKID} -o value -s PTTYPE "${DEVICE}")
     DEVICE_SIZE=$(cat "/sys/block/${DEVICE_NAME}/size")
     END_SIZE=$((DEVICE_SIZE - 1))
@@ -69,13 +71,13 @@ case "$1" in
   start)
     reboot=false
 
-    echo "Expanding rootfs..."
+    echo "Expanding last partition..."
 
     if do_expand_rootfs  ;
     then
       echo "Expanding partition success"
     else
-      echo "Expanding rootfs has failed, see log files. Error code: $?"
+      echo "Expanding partition has failed, see log files. Error code: $?"
     fi
 
     update-rc.d -f resize-rootfs remove >/dev/null 2>&1
