chg: dev: adjust wic partition params and fstab, cleanup license handling
* switch data partition to ext4, refactor resize-helper script using
  fdisk instead of sgdisk, adjust recipe deps
* use core license file in recipe and SPDX id in script file

Signed-off-by: Stephen L Arnold <sarnold@vctlabs.com>

diff --git a/recipes-core/resize-helper/files/resize-helper b/recipes-core/resize-helper/files/resize-helper
--- a/recipes-core/resize-helper/files/resize-helper
+++ b/recipes-core/resize-helper/files/resize-helper
@@ -1,43 +1,54 @@
 #!/bin/sh
 
+# SPDX-License-Identifier: BSD-2-Clause
+
+# Copyright (c) Fathi Boudra <fathi.boudra@linaro.org>
+# Copyright (c) Stephen Arnold <sarnold@vctlabs.com>
+# All rights reserved.
+
 set -e
 
 # we must be root
 [ $(whoami) = "root" ] || { echo "E: You must be root" && exit 1; }
-
-# we must have few tools
-SGDISK=$(which sgdisk) || { echo "E: You must have sgdisk" && exit 1; }
-PARTED=$(which parted) || { echo "E: You must have parted" && exit 1; }
-PARTPROBE=$(which partprobe) || { echo "E: You must have partprobe" && exit 1; }
-RESIZE2FS=$(which resize2fs) || { echo "E: You must have resize2fs" && exit 1; }
-BLKID=$(which blkid) || { echo "E: You must have blkid" && exit 1; }
 
 # find root device
 ROOT_DEVICE=$(findmnt / -o source -n)
 # prune root device (for example UUID)
 ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
 echo "Found root device: $ROOT_DEVICE"
-# get the partition number and type
+# get the partition number
 ROOT_PART_NAME=$(echo "$ROOT_DEVICE" | cut -d "/" -f 3)
 DEVICE_NAME=$(echo /sys/block/*/"${ROOT_PART_NAME}" | cut -d "/" -f 4)
-DEVICE="/dev/${DEVICE_NAME}"
+BASE_DEV="/dev/${DEVICE_NAME}"
 # get the last partition whether root or not
-PART_ENTRY_NUMBER=$(ls /sys/block/${DEVICE_NAME}/*/partition | wc -l)
-echo "Expanding part number: $PART_ENTRY_NUMBER"
-PART_TABLE_TYPE=$(${BLKID} -o value -s PTTYPE "${DEVICE}")
-DEVICE_SIZE=$(cat "/sys/block/${DEVICE_NAME}/size")
-END_SIZE=$((DEVICE_SIZE - 1))
+PART_NUM=$(ls /sys/block/${DEVICE_NAME}/*/partition | wc -l)
+echo "Expanding part number: $PART_NUM"
 
-# in case the root device is not on a partitioned media
-if [ "x$PART_ENTRY_NUMBER" = "x" ]; then
-    ${RESIZE2FS} "${ROOT_DEVICE}"
-    exit 0
-fi
+# Get the starting offset of the root partition
+PART_START=$(parted ${BASE_DEV} -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d:)
+# Remove suffix:
+PART_START=${PART_START%s}
+echo "resizing last partition, starts at offset: $PART_START"
+[ "$PART_START" ] || return 5
 
-if [ "$PART_TABLE_TYPE" = "gpt" ]; then
-    ${SGDISK} -e ${DEVICE}
-    ${PARTPROBE}
-fi
-${PARTED} ${DEVICE} resizepart ${PART_ENTRY_NUMBER} 100%
-${PARTPROBE}
-${RESIZE2FS} "${ROOT_DEVICE}"
+# Return value will likely be error for fdisk as it fails to reload the
+# partition table because the root fs is mounted
+fdisk ${BASE_DEV} <<EOF > /dev/null 2>&1
+p
+d
+$PART_NUM
+n
+p
+$PART_NUM
+$PART_START
+
+p
+w
+EOF
+
+sync
+echo "Probing the partition table ... "
+partprobe
+
+echo "Resizing partition ${BASE_DEV}p${PART_NUM} ... "
+resize2fs ${BASE_DEV}p${PART_NUM} || return $?
